### ISSUE TITLE
Produção UC - Auth

### ISSUE THREAD

**Issue by CassianoJunior** [es20231/eqp7#11]
## Casos de uso

- [x] Cadastro de usuário - UC1
- [x] Login do usuário - UC2
- [x] Logout do usuário - UC3
## Documento
[Link para especificação dos casos de uso](https://docs.google.com/document/d/16_a7VcDLfiBnNSRDkAK-I-4s3Ji1ly519rwJulKCqok/edit?usp=sharing)

**Comment by CassianoJunior** [comment]
Coloquei meus comentários no documento, da uma olhada.

**Comment by Amarildo-Jr** [comment]
@CassianoJunior fiz as alterações lá do que achei de acordo com o propósito.

**Comment by CassianoJunior** [comment]
E tu fechou pq msm? Ainda tem os outros pra dar review

**Comment by Amarildo-Jr** [comment]
Cliquei sem querer no "Close with comment"

**Comment by CassianoJunior** [comment]
LGTM.

Vou fechar essa também.

**Comment by CassianoJunior** [comment]
Professor disse que as pré-condições de um caso de uso derivado de outro caso de uso não precisa conter todas as pré-condições aninhadas, como o @EduardoRibeiroBR tinha falado. 
Reabrindo para modificações.
