### ISSUE TITLE
Produção UC - Controle de comentários

### ISSUE THREAD

**Issue by CassianoJunior** [es20231/eqp7#12]
## Casos de uso

- [x] Remover post - UC7
- [x] Comentar em um post - UC8
- [x] Remover comentário - UC9

**Comment by JoseeAugusto** [comment]
https://docs.google.com/document/d/17GG9Y_2unWhLvvVnAl1sziKQj6TWtJayTgEYgLU7pMM/edit?usp=sharing

Digam se tá tudo ok, para depois adicionar no artefato principal

**Comment by CassianoJunior** [comment]
1. Acho que no protótipo de `remover post` tem mais informação do que deveria. Dá a ênfase em um post só, e tenta criar um *dropdown menu* nesse botão `opções`. E esse botão também ta pouco visível e notável, dá mais enfoque pra ele.

2. Na precondição desse mesmo caso de uso, não é imagem e sim post.

3. O protótipo não pode ter especificações de como um botão tem que ser. Assim, no protótipo de `comentar em um post` tu colocou "ícone de seta", "ícone de balão". Isso já está atrelando à design, deixa só um botão `enviar/comentar` mesmo, que nem tu fez no botão `opções` no caso de uso de remover.

4. Acho que também é melhor deixar a opção de remover post isolada, sem poder excluir enquanto tá querendo comentar.

Obs: Habilita os comentários no documento, pra facilitar a revisão.

**Comment by JoseeAugusto** [comment]
Modificações realizadas.

**Comment by CassianoJunior** [comment]
LGTM. 

Revisem @Amarildo-Jr @EduardoRibeiroBR @assis23

**Comment by EduardoRibeiroBR** [comment]
As ações relacionadas ao acionamento de comandos não podem ser específicas. 

Como por exemplo: em vez de "clique" ou "o usuário clica no botão xxx", seria "O usuário aciona o comando xxx".

Dessa forma o protótipo fica genérico e serve para diferentes plataformas de acesso. Ex: celular ("toque na tela"), computador ("clique na tela"), etc... 

Além disso, nos exemplos do professor, os verbos são sempre conjugados no presente. Ex: "O usuário pode selecionar...."

**Comment by Amarildo-Jr** [comment]
Acredito que após as correções que foram feitas está bem completo.

**Comment by JoseeAugusto** [comment]
Modificações realizadas.

**Comment by CassianoJunior** [comment]
Acho que essa já tá certinha também, vou fechar.

**Comment by CassianoJunior** [comment]
Professor disse que as pré-condições de um caso de uso derivado de outro caso de uso não precisa conter todas as pré-condições aninhadas, como o @EduardoRibeiroBR tinha falado. 
Reabrindo para modificações.

**Comment by JoseeAugusto** [comment]
Modificações realizadas.
