### ISSUE TITLE
Produção UC - Perfil/Pesquisa

### ISSUE THREAD

**Issue by CassianoJunior** [es20231/eqp7#14]
## Casos de uso

- [x] Pesquisa de usuário - UC14
  - [x] Protótipo
  - [x] Fluxos
    - [x] Principal
    - [x] Alternativo
    - [x] Exceção
- [x] Detalhes do perfil de um usuário - UC15
  - [x] Protótipo
  - [x] Fluxos
    - [x] Principal
    - [x] Alternativo
    - [x] Exceção
      - Não possui
- [x] Editar dados do usuário - UC16
  - [x] Protótipo
  - [x] Fluxos
    - [x] Principal
    - [x] Alternativo
      - Não possui 
    - [x] Exceção

**Comment by CassianoJunior** [comment]
## Caso de Uso UC12

  - Nome: Pesquisa de usuário
  - Referente ao requisito:
  - Precondições:
      - O usuário precisa estar logado.
      - O usuário está na página que lista os usuários.
  - Fluxo principal
      1. O usuário digita na caixa de pesquisa.
      2. O MinIG filtra automaticamente os resultados dos usuários pré-carregados, usando como base de comparação o nome de usuário, nome completo ou email.
  - Fluxo alternativo
      1. O usuário digita na caixa de pesquisa.
      2. O usuário clica no botão de pesquisar.
      3. O sistema busca todos os usuários que possuem alguma parte do que foi digitado no nome completo, nome de usuário ou email e retorna para o usuário.
  - Fluxo de exceção
      1. O usuário não digita nada na caixa de pesquisa e clica no botão de pesquisar.
      2. O sistema detecta que não há nada na pesquisa e emite um aviso ao usuário.
   
## Caso de Uso UC13

  - Nome: Detalhes do perfil de um usuário
  - Referente ao requisito:
  - Precondições:
      - O usuário precisa estar logado.
      - O usuário está na página que lista os usuários.
  - Fluxo principal
      1. O usuário logado clica em um dos usuários listados pelo sistema.
      2. O sistema busca as informações desse usuário.
      3. O sistema exibe uma tela, mostrando as informações públicas do usuário clicado (nome completo, nome de usuário, biografia, foto de perfil), além de todos os seus posts, organizados de acordo com a data de postagem, de forma decrescente.
  - Fluxo alternativo
      1. O usuário realiza uma pesquisa.
      2. O usuário logado clica em um dos usuários filtrados pelo sistema.
      3. O sistema busca as informações desse usuário.
      4. O sistema exibe uma tela, mostrando as informações públicas do usuário clicado (nome completo, nome de usuário, biografia, foto de perfil), além de todos os seus posts, organizados de acordo com a data de postagem, de forma decrescente.
  - Fluxo de exceção
  - 
## Caso de Uso UC14

  - Nome: Editar dados do usuário
  - Referente ao requisito:
  - Precondições:
      - O usuário precisa estar logado
      - O usuário está na página do seu perfil.
  - Fluxo principal
      1. O usuário clica no botão de editar perfil.
      2. O MinIG habilita a edição dos dados do usuário mutáveis (nome completo, biografia e foto de perfil).
      3. O usuário realiza as mudanças que deseja.
      4. O sistema processa as informações, persiste e mostra os dados atualizados.
  - Fluxo alternativo
  - Fluxo de exceção
      1. O usuário clica no botão de editar perfil.
      2. O MinIG habilita a edição dos dados do usuário mutáveis (nome completo, biografia e foto de perfil).
      3. O usuário realiza mudanças não válidas nos dados mutáveis (nome completo vazio, biografia vazia, imagem no formato ou tamanho inválidos).
      4. O sistema alerta o usuário e não persiste as mudanças.

**Comment by EduardoRibeiroBR** [comment]
As ações relacionadas ao acionamento de comandos não podem ser específicas. 

Como por exemplo: em vez de "clique" ou "o usuário clica no botão xxx", seria "O usuário aciona o comando xxx".

Dessa forma o protótipo fica genérico e serve para diferentes plataformas de acesso. Ex: celular ("toque na tela"), computador ("clique na tela"), etc...

**Comment by CassianoJunior** [comment]
Entendi, faz sentido.

**Comment by CassianoJunior** [comment]
## Caso de Uso UC12

  - Nome: Pesquisa de usuário
  - Referente ao requisito:
  - Protótipo de tela:
  
![UseCase12](https://gist.githubusercontent.com/CassianoJunior/e2c7ae2bbe9de958632559b4b30b6ee4/raw/d8fd73d2be41b92145f0572293658c773a61b646/MinIG-UC12.png)

- Precondições:

  1. O usuário precisa estar logado.
  2. O usuário está na página que lista os usuários.

- Fluxo principal
  1. O usuário digita na área de pesquisa.
  2. O MinIG filtra automaticamente os resultados dos usuários pré-carregados, usando como base de comparação o nome de usuário, nome completo ou email.
- Fluxo alternativo
  1. O usuário digita na área de pesquisa.
  2. O usuário aciona a ação de pesquisar.
  3. O sistema busca todos os usuários que possuem alguma parte do que foi digitado no nome completo, nome de usuário ou email e retorna para o usuário.
- Fluxo de exceção
  1. O usuário não digita nada na área de pesquisa e aciona a função de pesquisar.
  2. O sistema detecta que não há nada na pesquisa e emite um aviso ao usuário.
   
## Caso de Uso UC13

- Nome: Detalhes do perfil de um usuário
- Referente ao requisito:
- Protótipo de tela:

![UseCase13](https://gist.githubusercontent.com/CassianoJunior/e2c7ae2bbe9de958632559b4b30b6ee4/raw/d8fd73d2be41b92145f0572293658c773a61b646/MinIG-UC13.png)

- Precondições:
  - O usuário precisa estar logado.
  - O usuário está na página que lista os usuários.
- Fluxo principal
  1. O usuário logado aciona a ação de visualizar um dos usuários listados pelo sistema.
  2. O sistema busca as informações desse usuário.
  3. O sistema exibe uma tela, mostrando as informações públicas do usuário escolhido (nome completo, nome de usuário, biografia, foto de perfil), além de todos os seus posts, organizados de acordo com a data de postagem, de forma decrescente.
- Fluxo alternativo
  1. O usuário realiza a ação de pesquisar.
  2. O usuário logado aciona a ação de visualizar um dos usuários filtrados pelo sistema.
  3. O sistema busca as informações desse usuário.
  4. O sistema exibe uma tela, mostrando as informações públicas do usuário clicado (nome completo, nome de usuário, biografia, foto de perfil), além de todos os seus posts, organizados de acordo com a data de postagem, de forma decrescente.

## Caso de Uso UC14

- Nome: Editar dados do usuário
- Referente ao requisito:
- Protótipo de tela:

![UseCase14](https://gist.githubusercontent.com/CassianoJunior/e2c7ae2bbe9de958632559b4b30b6ee4/raw/7be3e2bec274f9fa4ead131a92f512c4e5abe503/MinIG-UC14.png)

- Precondições:
  - O usuário precisa estar logado
  - O usuário está na página do seu perfil.
- Fluxo principal
  1. O usuário aciona a ação de editar perfil.
  2. O MinIG habilita a edição dos dados do usuário mutáveis (nome completo, biografia e foto de perfil).
  3. O usuário realiza as mudanças que deseja.
  4. O sistema processa as informações, persiste e mostra os dados atualizados.
- Fluxo de exceção
  1. O usuário aciona a ação de editar perfil.
  2. O MinIG habilita a edição dos dados do usuário mutáveis (nome completo, biografia e foto de perfil).
  3. O usuário realiza mudanças não válidas nos dados mutáveis (nome completo vazio, biografia vazia, imagem no formato ou tamanho inválidos).
  4. O sistema alerta o usuário e não persiste as mudanças.

**Comment by JoseeAugusto** [comment]
LGTM.

**Comment by CassianoJunior** [comment]
Acho que essa já foi, vou marcar como conluída.
