### ISSUE TITLE
Diagrama de casos de uso

### ISSUE THREAD

**Issue by CassianoJunior** [es20231/eqp7#18]
## Diagrama

![Diagram](https://gist.githubusercontent.com/CassianoJunior/e2c7ae2bbe9de958632559b4b30b6ee4/raw/6e2a073f3d6a88025c158be7d011bd48c37f526d/use-cases.png)

**Comment by JoseeAugusto** [comment]
LGTM.

**Comment by EduardoRibeiroBR** [comment]
Bacana

**Comment by assis23** [comment]
Ok

**Comment by CassianoJunior** [comment]
Mudanças com os novos casos de uso de inserir e remover reações em comentários

**Comment by CassianoJunior** [comment]
## Diagrama

![UseCaseDiagram](https://gist.githubusercontent.com/CassianoJunior/e2c7ae2bbe9de958632559b4b30b6ee4/raw/77439fdfe9f5971acbbb7e1aad4167494e028607/UCD%2520-%2520MinIG.png)

**Comment by EduardoRibeiroBR** [comment]
- O usuário não pode clicar em "Pesquisar usuário" direto do Dashboard? Da forma como está parece que ele tem que acessar o feed antes. (Tem feed mesmo?).

-> A forma como "Gerenciar post" está agora difere dos casos de uso:
 
- Eu removeria "Listar imagens", substituiria por "Interação com imagem".
- Após "Interação com imagem" viria: "Remover imagem" e outra seta para "Criar post". Como está nos protótipos.
- No lugar de "gerenciar posts", colocaria "Interação com Post". Deste sairiam as seguintes setas: "Remover post", "Ver todos os comentários do post", "Remover reações do post", "Interação com comentário".
- Depois de "Interação com comentário" viria "Remover reações dos comentários". Tal como está no protótipo
- Depois de "Ver todos os comentários do post" viria "Remover comentário".

Obs: Interação seria um clique ou um toque na tela.
Relevem algum erro, fiz rápido

**Comment by EduardoRibeiroBR** [comment]
Acho que para inserir reações nos comentários o usuário interage com o comando "Ver todos os comentários do post". Ou seja, teria dois quadradinhos azul deste. Um para o próprio post e outro quando acessando o post de outro usuário

**Comment by CassianoJunior** [comment]
> * O usuário não pode clicar em "Pesquisar usuário" direto do Dashboard? Da forma como está parece que ele tem que acessar o feed antes. (Tem feed mesmo?).
> 
> -> A forma como "Gerenciar post" está agora difere dos casos de uso:
> 
> * Eu removeria "Listar imagens", substituiria por "Interação com imagem".
> * Após "Interação com imagem" viria: "Remover imagem" e outra seta para "Criar post". Como está nos protótipos.
> * No lugar de "gerenciar posts", colocaria "Interação com Post". Deste sairiam as seguintes setas: "Remover post", "Ver todos os comentários do post", "Remover reações do post", "Interação com comentário".
> * Depois de "Interação com comentário" viria "Remover reações dos comentários". Tal como está no protótipo
> * Depois de "Ver todos os comentários do post" viria "Remover comentário".
> 
> Obs: Interação seria um clique ou um toque na tela. Relevem algum erro, fiz rápido

É pra ter feed sim. Basicamente o nosso botão de listar usuários vai ser esse "Feed".

Não acho que devemos levar esses protótipos como fixos, até porque são protótipos, vão e devem mudar. 
Mas as alterações nos casos de uso fazem sentido, vou alterar aqui

**Comment by CassianoJunior** [comment]
## Diagrama 

![UCD](https://gist.githubusercontent.com/CassianoJunior/e2c7ae2bbe9de958632559b4b30b6ee4/raw/5573c40a316fb507209a249fc4167d0f4cac3d25/UCD%2520-%2520MinIG.png)

**Comment by EduardoRibeiroBR** [comment]
Beleza, bacana, acho que descreve bem as etapas de interação no nosso app.
