### ISSUE TITLE
Diagrama de componentes

### ISSUE THREAD

**Issue by CassianoJunior** [es20231/eqp7#19]
## Diagrama no modelo C4

![C4 Model Diagram](https://gist.githubusercontent.com/CassianoJunior/e2c7ae2bbe9de958632559b4b30b6ee4/raw/01c3caa1146c49f391f2387f240e274a7c7d808b/MinIG%2520Architecture.png)

Deem uma sugestão do que colocar nessa descrição do sistema web, fiquei sem ideia do que colocar.

**Comment by EduardoRibeiroBR** [comment]
ok

**Comment by JoseeAugusto** [comment]
LGTM.

**Comment by CassianoJunior** [comment]
Nenhuma sugestão pra descrever a aplicação web?

No exemplo dele tinha: `Allows users to analysis git repositories`.
Basicamente um resumo sobre a aplicação.

**Comment by JoseeAugusto** [comment]
Algo tipo "Interconecta os demais componentes da aplicação"

**Comment by CassianoJunior** [comment]
Não, pelo contexto do que o professor fez, não faz nenhum sentido isso. Seria basicamente uma descrição da aplicação como um todo.

**Comment by JoseeAugusto** [comment]
Pois então eu deixaria do jeito que tá mesmo.

**Comment by CassianoJunior** [comment]
## Diagrama usando o modelo c4

![C4Model](https://gist.githubusercontent.com/CassianoJunior/e2c7ae2bbe9de958632559b4b30b6ee4/raw/0b2d3184a61c6ba338f8977aa96efd2c2d7a63e8/MinIG%2520Architecture.png)

**Comment by CassianoJunior** [comment]
Assim ta bom, vou fechar essa também
