### ISSUE TITLE
Diagrama Entidade Relacionamento

### ISSUE THREAD

**Issue by CassianoJunior** [es20231/eqp7#20]
## Diagrama

![DER](https://gist.githubusercontent.com/CassianoJunior/e2c7ae2bbe9de958632559b4b30b6ee4/raw/7e04ade5cb1efe05164ec0085eb53eb416d77bb8/MinIG%2520-%2520DER.png)

**Comment by CassianoJunior** [comment]
Vejam se tem rumo isso aqui @EduardoRibeiroBR @Amarildo-Jr @JoseeAugusto @assis23 

![DER](https://gist.githubusercontent.com/CassianoJunior/e2c7ae2bbe9de958632559b4b30b6ee4/raw/d0008c7f7c5cf9c4568f4303cc5525d4f3bf6abd/MinIG%2520-%2520DER-draft.png)

**Comment by CassianoJunior** [comment]
## Diagram com plantuml

![ERD](https://gist.githubusercontent.com/CassianoJunior/e2c7ae2bbe9de958632559b4b30b6ee4/raw/0833cf1b6946b39fa511f785b156254b8040e4b0/Entity%2520Relationship%2520Diagram%2520-%2520MinIG.png)

**Comment by EduardoRibeiroBR** [comment]
oK

**Comment by CassianoJunior** [comment]
Queria que alguém conferisse se as relações de agregação e composição fazem sentido.

**Comment by assis23** [comment]
LGTM.

**Comment by CassianoJunior** [comment]
Alterações: Classes diferentes para reação em comentários e posts
