### ISSUE TITLE
Produção UC - Controle de reações em comentários (like/deslike)

### ISSUE THREAD

**Issue by CassianoJunior** [es20231/eqp7#24]
## Casos de uso

- [x] Inserir reação em comentário - UC12
  - [x] Protótipo
  - [x] Fluxos
    - [x] Principal
    - [x] Alternativo
    - [x] Exceção
- [x] Remover reação em comentário - UC13
  - [x] Protótipo
  - [x] Fluxos
    - [x] Principal
    - [x] Alternativo
    - [x] Exceção

**Comment by CassianoJunior** [comment]
## Caso de Uso UC12

  - Nome: Inserir reação em comentário
  - Referente ao requisito:
  - Protótipo de tela:
  
![UseCase12]()

- Precondições:
  - O usuário precisa estar logado.
  - O usuário está visualizando um post.
  - O post visualizado precisa ter pelo menos um comentário.
- Fluxo principal
  1. O usuário realiza a ação de inserir uma reação em um comentário.
  2. O MinIG registra essa reação no comentário selecionado e persiste no sistema.
- Fluxo alternativo:
  - Não possui
- Fluxo de exceção
  - Não possui
 
## Caso de uso UC13

  - Nome: Remover reação em comentário (**)
  - Referente ao requisito:
  - Protótipo de tela:
  
![UseCase13]()

- Precondições:
  - O usuário precisa estar logado.
  - O usuário está visualizando um post.
  - O post visualizado precisa ter pelo menos um comentário.
  - O comentário selecionado precisa ter ao menos uma reação.
- Fluxo principal
  1. O usuário realiza a ação de remove uma reação em um comentário.
  2. O MinIG remove essa reação no comentário selecionado e persiste no sistema.
- Fluxo alternativo:
  - Não possui
- Fluxo de exceção
  - Não possui

**Comment by JoseeAugusto** [comment]
No UC 12, tentar inserir duas reações no mesmo comentário não seria um fluxo de exceção?

**Comment by EduardoRibeiroBR** [comment]
> No UC 12, tentar inserir duas reações no mesmo comentário não seria um fluxo de exceção?

Na minha visão, se o cara der like, remove o deslike, e virse-versa. Ou é um ou outro

**Comment by JoseeAugusto** [comment]
Faz sentido.

**Comment by JoseeAugusto** [comment]
LGTM.

**Comment by CassianoJunior** [comment]
Nao, o usuário não pode modificar a sua reação. Isso eu lembro. Clicou em
like, morreu, fica o like. A não ser que o dono do post retire sua reacao.
Mesma coisa pro deslike.

**Comment by CassianoJunior** [comment]
Acho que é isso, vou marcar como concluída essa aqui

**Comment by CassianoJunior** [comment]
Professor disse que as pré-condições de um caso de uso derivado de outro caso de uso não precisa conter todas as pré-condições aninhadas, como o @EduardoRibeiroBR tinha falado. 
Reabrindo para modificações.
