### ISSUE TITLE
Bug atualizar post

### ISSUE THREAD

**Issue by CassianoJunior** [es20231/eqp7#61]
Atualizando post com imagem que não existe, com usuário que não existe e retornando apenas o que foi atualizado em vez da entidade Post completa

**Comment by armandossrecife** [comment]
Uma boa prática é fazer o registro do bug em uma issue do repositório e associar ao responsável pelo bug-fix. Após o bug-fix, gere uma nova build/release, lembre-se de rodar os testes novamente e se tudo passar então libere a release estável.
